name: Node.js Deployment

jobs:
  test:
    runs-on: xyzrunner
    - run: npm install
    - run: npm run test
  build:
    runs-on: xyzrunner
    steps:
      - run: docker build -t test-app:latest .
  push-to-reg:
    - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}